version: '3'

services:
  angular:
    build: angular-app
    ports:
      - "4200:4200"
    volumes:
      - ./angular-app:/app

  express:
    build: express-server
    ports:
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
